### ISSUE TITLE
Run Playbooks - Returning Error in CLI, but Playbook Run is Success in UI

### ISSUE THREAD

**Issue by jacognigy** [Cognigy/Cognigy-CLI#145]
I'm using the command for "run playboosk": https://github.com/Cognigy/Cognigy-CLI#command-run

When I run the command with a test config file (with just 1 playbook) I get the following error:
```
jna@x-x:~$ cognigy run playbooks playbook_test.json
/home/jna/.nvm/versions/node/v18.15.0/lib/node_modules/@cognigy/cognigy-cli/build/utils/RestAdapter.js:76
        throw new BadRequestError_1.BadRequestError(data.title || data.error, data.detail || data.error_description, data.status, data.details);
              ^

Not Found: Playbook run does not exist
    at RestAdapter.handleError (/home/jna/.nvm/versions/node/v18.15.0/lib/node_modules/@cognigy/cognigy-cli/build/utils/RestAdapter.js:76:15)
    at RestAdapter.request (/home/jna/.nvm/versions/node/v18.15.0/lib/node_modules/@cognigy/cognigy-cli/build/utils/RestAdapter.js:42:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/jna/.nvm/versions/node/v18.15.0/lib/node_modules/@cognigy/cognigy-cli/node_modules/@cognigy/rest-api-client/build/GenericAPIFn.js:12:26
    at async Timeout._onTimeout (/home/jna/.nvm/versions/node/v18.15.0/lib/node_modules/@cognigy/cognigy-cli/build/lib/playbooks.js:71:37) {
  msg: 'Playbook run does not exist',
  httpStatusCode: 404,
  httpStatusText: 'Not Found',
  details: {}
}

Node.js v18.15.0
```

However, when I log into the UI of the Platform I can see the run from the Playbook with status succeeded.

I've tried adjusting the config.json file to update the timeout, but it doesn't wait as long as identified before the error is returned (ex. I set it to 30 or 60, and it's just as short as 10).

**Comment by XavierJordaMurria** [comment]
Hi,
thanks for reporting this.
I will create a ticket to investigate this.
I will let you know once we schedule it in.

**Comment by Heikum** [comment]
@XavierJordaMurria this is still the case

Any updates?

**Comment by XavierJordaMurria** [comment]
Hi,
@Heikum @jacognigy 
Could you please provide a  *.tar file a snapshot (with playbook and flow), plus the playbooks.json file used on the cli?

I did run a simple playbook locally and it worked.
![image](https://github.com/user-attachments/assets/17507509-b772-4c27-b213-7e9264daf1dc)

**Comment by mohammedalibaddah** [comment]
@XavierJordaMurria how do we generate the playbooks.json file exactly?

**Comment by mohammedalibaddah** [comment]
I'm experiencing the same issue as @jacognigy

**Comment by ohiobobcat** [comment]
We're having the same problem

**Comment by KeiKey** [comment]
Hi @Heikum @ohiobobcat @mohammedalibaddah,

I'm following this issue and getting successful runs from the command. Could you please provide the information in the format Xavier previously requested so I can test with your flow and playbook?

Thanks!


> Hi, [@Heikum](https://github.com/Heikum) [@jacognigy](https://github.com/jacognigy) Could you please provide a *.tar file a snapshot (with playbook and flow), plus the playbooks.json file used on the cli?

**Comment by KeiKey** [comment]
Hi @Heikum @ohiobobcat @mohammedalibaddah 

A follow up for this issue. We have release a fix for the issue being faced. Please let us know
