### ISSUE TITLE
clone of cognigy agent fails

### ISSUE THREAD

**Issue by panovodv** [Cognigy/Cognigy-CLI#82]
(base) petrn@ip-10-10-2-121 accsec % cognigy clone                                                                    
? This will delete all agent data you have stored currently locally. Do you want to proceed? Yes
Starting to clone your Agent to disk. This can take several minutes... 

 ██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░ 35% | ETA: 3s | 35/100/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/utils/checks.js:68
        return Promise.reject(new Error(task.failReason));
                              ^

Error: The keyphrase '66' is not allowed in a csv download because it starts with a forbidden character. This is to prevent csv/Excel injection.
    at exports.checkTask (/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/utils/checks.js:68:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.pullLexicon (/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/lib/lexicons.js:58:5)
    at async exports.cloneLexicons (/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/lib/lexicons.js:26:9)
    at async Promise.all (index 2)
    at async exports.clone (/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/commands/clone.js:31:13)
    at async Command.<anonymous> (/opt/homebrew/lib/node_modules/@cognigy/cognigy-cli/build/program.js:37:33)

Node.js v19.5.0

--
I believe this happens because Lexicon contains "+66" country code as a value.

**Comment by XavierJordaMurria** [comment]
yes, that is right.
if you remove the "+" it should work

**Comment by panovodv** [comment]
@XavierJordaMurria my lexicon contains + in the words as these are phone codes. Is it possible to allow + in lexicon words or is it explicitly prohibited?

**Comment by XavierJordaMurria** [comment]
@panovodv right now it is explicitly prohibited.
You should open a feature request, but I would suggest to use the '00' instead; +66 = 0066
